# python pass_curve.py --model gpt-oss-20b --dataset math500 --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset svamp --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset gpqa-main --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset gpqa-diamond --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset scibench --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset aime24 --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model gpt-oss-20b --dataset aime25 --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset gpqa-diamond --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python pass_curve.py --model Qwen2.5-7B-Instruct --dataset math500 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_avgdis2.json
python pass_curve.py --model Qwen2.5-7B-Instruct --dataset aime24 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_avgdis2.json
python pass_curve.py --model Qwen2.5-7B-Instruct --dataset aime25 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_avgdis2.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset gpqa-main --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset gpqa-main --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset gpqa-diamond --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset scibench --sc_file generated_answers_20samples.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset aime24 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve.py --model Qwen2.5-32B-Instruct --dataset aime25 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
# python pass_curve1.py --model Qwen2.5-7B-Instruct --dataset math500 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file_1 logic_tree_results_all_leaves20_threshold90_ddp_relevance.json --lt_file_2 logic_tree_results_all_leaves20_threshold80_ddp_relevance_random.json --lt_file_3 logic_tree_results_all_leaves20_threshold80_ddp_relevance.json