# python diversity.py --model Qwen2.5-7B-Instruct --dataset svamp --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset math500 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset scibench --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset gpqa-main --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset gpqa-diamond --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset aime24 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-7B-Instruct --dataset aime25 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset svamp --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset math500 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset scibench --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset gpqa-main --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset gpqa-diamond --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset aime24 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
# python diversity.py --model Qwen2.5-14B-Instruct --dataset aime25 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_ddp_relevance.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset svamp --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset math500 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset scibench --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset gpqa-main --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset gpqa-diamond --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset aime24 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json
python diversity.py --model Qwen2.5-32B-Instruct --dataset aime25 --sc_file generated_answers_20samples_ray_8gpus.json --lt_file logic_tree_results_all_leaves20_threshold80_tpdp.json